---
---

$ ->
  return if window.rendererTradeLeadMapping?

  window.rendererTradeLeadMapping = {}
  window.rendererTradeLeadMapping.fieldsBySource = {
    AUSTRALIA: [
      'title',
      'country_name',
      'amt_id',
      'agency',
      'publish_date',
      'end_date',
      'url',
      'location',
      'multi_agency_access',
      'panel_arrangement',
      'other_instructions',
      'conditions_for_participation',
      'delivery_timeframe',
      'lodgement_address',
      'description',
      'contact_officer',
      'phone',
      'email',
    ],
    CANADA: [
      'title',
      'country_name',
      "contract_number",
      'reference_number',
      "amendment_number",
      "notice_type",
      "publishing_status",
      'publish_date',
      'publish_date_amended',
      'end_date',
      "url",
      "specific_location",
      "trade_agreement",
      "bid_type",
      "competitive_procurement_strategy",
      "procurement_organization",
      "implementing_entity",
      "description",
      "contact",
    ],
    FBO: [
      'title',
      'country_name',
      'contract_number',
      'notice_type',
      'publish_date',
      'end_date',
      'url',
      'procurement_organization',
      'procurement_office',
      'procurement_organization_address',
      'classification_code',
      'procurement_office_address',
      'competitive_procurement_strategy',
      'specific_address',
      'description',
      'contact',
    ],
    MCA: [
      "title",
      "country_name",
      "publish_date",
      "url",
      "description"
    ],
    STATE: [
      "title",
      "country_name",
      "record_id",
      "project_number",
      "project_size",
      "lead_source",
      "status",
      "publish_date",
      "end_date",
      "url",
      "tags",
      "funding_source",
      "borrowing_entity",
      "procurement_organization",
      "specific_location",
      "description",
      "comments",
      "contact",
      "submitting_officer",
      "submitting_officer_contact",
    ],
    UK: [
      "title",
      "country_name",
      "record_id",
      "reference_number",
      "notice_type",
      "status",
      "publish_date",
      "deadline_date",
      "contract_start_date",
      "contract_end_date",
      "min_contract_value",
      "max_contract_value",
      "url",
      "procurement_organization",
      "description",
      "specific_location",
      "contact",
    ],
    USTDA: [
      "title",
      "country_name",
      "publish_date",
      "end_date",
      "url",
      "description"
    ]
  }

  window.rendererTradeLeadMapping.friendlyNames = {
    agency: 'Agency',
    amendment_number: 'Amendment number',
    amt_id: 'ATM ID',
    bid_type: 'Bid type',
    borrowing_entity: 'Borrowing entity',
    classification_code: 'Classification code',
    comments: 'Comments',
    competitive_procurement_strategy: 'Competitive procurement strategy',
    conditions_for_participation: 'Conditions for participation',
    contact: 'Contact',
    contact_officer: 'Contact officer',
    contract_end_date: 'Contract end date',
    contract_number: 'Contract number',
    contract_start_date: 'Contract start date',
    country_name: 'Country',
    deadline_date: 'Deadline date',
    delivery_timeframe: 'Delivery timeframe',
    description: 'Description',
    email: 'Email',
    end_date: 'End date',
    funding_source: 'Funding source',
    implementing_entity: 'Implementing entity',
    lead_source: 'Lead source',
    location: 'Location',
    lodgement_address: 'Lodgement address',
    max_contract_value: 'Max contract value',
    min_contract_value: 'Min contract value',
    multi_agency_access: 'Multi agency access',
    notice_type: 'Notice type',
    other_instructions: 'Other instructions',
    panel_arrangement: 'Panel arrangement',
    phone: 'Phone',
    procurement_office: 'Procurement office',
    procurement_office_address: 'Procurement office address',
    procurement_organization: 'Procurement organization',
    procurement_organization_address: 'Procurement organization address',
    project_number: 'Project number',
    project_size: 'Project size',
    publish_date: 'Publish date',
    publish_date_amended: 'Amendment date',
    publishing_status: 'Publishing status',
    record_id: 'Record',
    reference_number: 'Reference number',
    specific_address: 'Specific address',
    specific_location: 'Specific location',
    status: 'Status',
    submitting_officer: 'Submitting officer',
    submitting_officer_contact: 'Submitting officer contact',
    tags: 'Tags',
    title: 'Title',
    trade_agreement: 'Trade agreement',
    url: 'URL' }

#  window.rendererTradeLeadMapping.friendlyNames = {
#    agency: 'Agency',
#    bid_type: 'Bid type',
#    borrowing_entity: 'Borrowing entity',
#    categories: 'Categories',
#    classification_code: 'Classification code',
#    comments: 'Comments',
#    competitive_procurement_strategy: 'Competitive procurement strategy',
#    contact: 'Contact',
#    contract_number: 'Contract number',
#    contract_value: 'Contract value',
#    country_name: 'Country',
#    description: 'Description',
#    end_date: 'End date',
#    funding_source: 'Funding source',
#    implementing_entity: 'Implementing entity',
#    ita_industries: 'Industries',
#    lead_source: 'Lead source',
#    max_contract_value: 'Max contract value',
#    min_contract_value: 'Min contract value',
#    non_competitive_procurement_strategy: 'Non competitive procurement strategy',
#    notice_type: 'Notice type',
#    parent_id: 'Parent',
#    procurement_method: 'Procurement method',
#    procurement_office: 'Procurement office',
#    procurement_office_address: 'Procurement office address',
#    procurement_organization: 'Procurement organization',
#    procurement_organization_address: 'Procurement organization address',
#    project_number: 'Project number',
#    project_size: 'Project size',
#    publish_date: 'Publish date',
#    publish_date_amended: 'Publish date amended',
#    reference_number: 'Reference number',
#    specific_address: 'Specific address',
#    specific_location: 'Specific location',
#    start_date: 'Start date',
#    status: 'Status',
#    submitting_officer: 'Submitting officer',
#    submitting_officer_contact: 'Submitting officer contact',
#    tags: 'Tags',
#    title: 'Title',
#    trade_agreement: 'Trade agreement',
#    trade_regions: 'Trade regions',
#    url: 'URL',
#    urls: 'URLs',
#    world_regions: 'World regions'
#  }
