---
---

$ ->
  return if window.rendererTradeEventMapping?

  window.rendererTradeEventMapping = {}
  window.rendererTradeEventMapping.fieldsBySource = {
    DL: [
      'click_url',
      'description',
      'hosted_url',
      'name',
      'source',
      'url'
    ],
    ITA: [
      'click_url',
      'contacts',
      'email',
      'first_name',
      'last_name',
      'person_title',
      'phone',
      'post',
      'cost',
      'description',
      'end_date',
      'event_type',
      'hosted_url',
      'industries',
      'name',
      'registration_title',
      'registration_url',
      'source',
      'start_date',
      'url',
      'venues',
      'city',
      'country',
      'name',
      'postal_code',
      'state',
      'street'
    ],
    SBA: [
      'contacts',
      'cost',
      'description',
      'end_date',
      'end_time',
      'name',
      'event_type',
      'hosted_url',
      'industries',
      'registration_url',
      'registration_click_url',
      'source',
      'start_date',
      'start_time',
      'time_zone',
      'venues'
    ],
    USTDA: [
      'contacts',
      'email',
      'first_name',
      'last_name',
      'person_title',
      'phone',
      'post',
      'click_url',
      'cost',
      'cost_currency',
      'description',
      'end_date',
      'end_time',
      'hosted_url',
      'industries',
      'name',
      'registration_title',
      'registration_url',
      'source',
      'start_date',
      'start_time',
      'url',
      'venues',
      'city',
      'country',
      'name',
      'postal_code',
      'state',
      'street'
    ]
  }

  window.rendererTradeEventMapping.friendlyNames = {
    city: 'City',
    click_url: 'Click URL',
    contacts: 'Contacts',
    cost: 'Cost',
    cost_currency: 'Cost Currency',
    country: 'Country',
    description: 'Description',
    email: 'Email',
    end_date: 'End Date',
    end_time: 'End Time',
    event_type: 'Event Type',
    first_name: 'First Name',
    hosted_url: 'Hosted URL',
    industries: 'Industries',
    last_name: 'Last Name',
    name: 'Name',
    person_title: 'Person Title',
    phone: 'Phone',
    post: 'Post',
    postal_code: 'Postal Code',
    registration_click_url: 'Registration Click URL',
    registration_title: 'Registration Title',
    registration_url: 'Registration URL',
    source: 'Source',
    start_date: 'Start Date',
    start_time: 'Start Time',
    state: 'State',
    street: 'Street',
    time_zone: 'Time Zone',
    url: 'URL'
    venues: 'Venues'}
